mycobot_gripper:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controller ---------------------------------------
    finger_joint_position_controller:
      type: position_controllers/JointTrajectoryController
      joints: 
       - left_outer_base_knuckle_joint
      gains:
        left_outer_base_knuckle_joint: {p: 1.0, i: 0, d: 0}


    

