mycobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

    # Arm Position Controller ---------------------------------------
  arm_joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints: 
     - arm1_joint
     - arm2_joint
     - arm3_joint
     - arm4_joint
     - arm5_joint
     - arm5_flange_joint
  finger_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: left_outer_base_knuckle_joint

  gains:
    arm1_joint:  {p: 60.0, i: 0, d: 0}
    arm2_joint:  {p: 20.0, i: 0, d: 0}
    arm3_joint:  {p:  6.0, i: 0, d: 0}
    arm4_joint:  {p:  2.0, i: 0, d: 0}
    arm5_joint:  {p:  2.0, i: 0, d: 0}
    arm5_flange_joint:  {p:  1.0, i: 0, d: 0}
    left_outer_base_knuckle_joint:  {p: 1.0, i: 0, d: 0}

    