mycobot:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    arm1_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: arm1_joint
      pid: {p: 100.0, i: 0.01, d: 0.1}
    arm2_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: arm2_joint
      pid: {p: 100.0, i: 0.01, d: 0.1}
    arm3_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: arm3_joint
      pid: {p: 100.0, i: 0.01, d: 0.1}
    arm4_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: arm4_joint
      pid: {p: 100.0, i: 0.01, d: 0.1}
    arm5_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: arm5_joint
      pid: {p: 100.0, i: 0.01, d: 0.1}
    arm5_flange_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: arm5_flange_joint
      pid: {p: 100.0, i: 0.01, d: 0.1}
