mycobot:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    arm1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: arm1_joint
      pid: {p: 60.0, i: 0, d: 0}
    arm2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: arm2_joint
      pid: {p: 20.0, i: 0, d: 0}
    arm3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: arm3_joint
      pid: {p: 6.0, i: 0, d: 0}
    arm4_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: arm4_joint
      pid: {p: 2.0, i: 0, d: 0}
    arm5_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: arm5_joint
      pid: {p: 2.0, i: 0, d: 0}
    arm5_flange_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: arm5_flange_joint
      pid: {p: 1.0, i: 0, d: 0}


